version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk

    working_directory: ~/circle-ci-test
    
    steps:
      # git pull
      - checkout

      # setup testing env
      - run: ./mvnw clean install
