version: 2
jobs:
  build:
    working_directory: ~/circle-ci-test

    docker:
      - image: circleci/openjdk:11.0.1-jdk-stretch
   
    steps:
      # git pull
      - checkout
      - restore_cache:
          key: circle-ci-test-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline # gets the project dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: circle-ci-test-{{ checksum "pom.xml" }}
      
      - run: mvn package

      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/rest-service-0.0.1-SNAPSHOT.jar
